[package]
name = "ds4-gpu"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
ds4-gguf = { path = "../ds4-gguf" }
ds4-gpu-sys = { path = "../ds4-gpu-sys" }

[features]
default = []
cuda-backend = []
cuda-rust-backend = ["cuda-backend"]

[lib]
path = "src/lib.rs"
