[package]
name = "ds4-gguf"
edition.workspace = true
version.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[[bin]]
name = "ds4-gguf-dump"
path = "src/bin/ds4-gguf-dump.rs"

[[bin]]
name = "ds4-dsml-dump"
path = "src/bin/ds4-dsml-dump.rs"

[[bin]]
name = "ds4-agent-dsml-dump"
path = "src/bin/ds4-agent-dsml-dump.rs"

[[bin]]
name = "ds4-sampling-dump-rs"
path = "src/bin/ds4-sampling-dump-rs.rs"
