[package]
name = "ds4-engine"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
ds4-gguf = { path = "../ds4-gguf" }

[lib]
path = "src/lib.rs"

[[bin]]
name = "ds4-inspect-runtime-rs"
path = "src/bin/ds4-inspect-runtime-rs.rs"

[[bin]]
name = "ds4-cli-inspect-rs"
path = "src/bin/ds4-cli-inspect-rs.rs"

[[bin]]
name = "ds4-argmax-runtime-rs"
path = "src/bin/ds4-argmax-runtime-rs.rs"

[[bin]]
name = "ds4-session-runtime-rs"
path = "src/bin/ds4-session-runtime-rs.rs"

[[bin]]
name = "ds4-runtime-official-vectors-rs"
path = "src/bin/ds4-runtime-official-vectors-rs.rs"

[[bin]]
name = "ds4-runtime-long-context-rs"
path = "src/bin/ds4-runtime-long-context-rs.rs"

[[bin]]
name = "ds4-cli-one-shot-rs"
path = "src/bin/ds4-cli-one-shot-rs.rs"

[[bin]]
name = "ds4-interactive-runtime-rs"
path = "src/bin/ds4-interactive-runtime-rs.rs"

[[bin]]
name = "ds4-cli-interactive-rs"
path = "src/bin/ds4-cli-interactive-rs.rs"

[[bin]]
name = "ds4-server-runtime-rs"
path = "src/bin/ds4-server-runtime-rs.rs"
